name = "Vanillish"
author = "Ryan Cao"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "143ed7f3026db85c0b18e48da6ea8b94549155abba8bf9dfed52e7dcaeff6033"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
