name = "Vanillish"
author = "Ryan Cao"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "261f81d0443cddc30f90c36027a884572f799a9fcccee3ddc8ae911f9e068ad2"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
