name = "Vanillish"
author = "Ryan Cao"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc4c3750f92b93213c396ba512bdf5509809616a168f6ab4971b490e0465aced"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
