name = "Vanillish"
author = "Ryan Cao"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61d45b6c5ebf54bad330c28967a0f69c6404529a459898bff169f8b5da9d596d"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"

[options]
acceptable-game-versions = ["1.19.3"]
