name = "Vanillish"
author = "Ryan Cao"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de618b9235ed673367587f81a721a9b45163188496b5a716ca0743bf15ee59ed"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
