name = "Vanillish"
author = "Ryan Cao"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "205def03169f91ad349e96d953f1eaeebe9813c5d2221f53a800ab4ef4d137a4"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
