name = "Vanillish"
author = "Ryan Cao"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e475c594536956c726da97527befd062ed1fa576cbb1ad3065a8b0e279e57bb"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
