name = "Vanillish"
author = "Ryan Cao"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04fcd47bf1a9eeac3409a8a126eacfe80bd579cd570d3f41dddbc18c485a82fc"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
