name = "Vanillish"
author = "Ryan Cao"
version = "0.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b982fbfd2aae74f2295ab059a500e77b24a312cb1d8752aefc7bb4d73a6452f"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
