name = "Vanillish"
author = "Ryan Cao"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25d340642202575c3da1e9f456c119f8c43675b16b0da58ae2e6972fde3bdcb5"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
